first commit
biocatchltd/ayelet_initmanager pull request #1
Opened 2022-06-22 14:52 UTC by AyeletKeren

2022-06-23 08:16 UTC, bentheiii requested changes

2022-06-23 08:16 UTC, bentheiii commented on tests/blackbox/conftest.py
> +            f'RABBIT_URL=amqp://guest:guest@{self.rabbitmq_host}:{self.rabbitmq_port}/guest',
why list the host and port twice?

2022-06-23 08:16 UTC, bentheiii commented on tests/blackbox/image/conftest.py
> +            ports={SERVICE_PORT: SERVICE_PORT},
don't autobind

```suggestion
            ports={SERVICE_PORT: 0},
```

2022-06-23 08:16 UTC, bentheiii commented on tests/blackbox/image/conftest.py
> +                print(msg, file=sys.stderr)
U2U but you can use yellowbox for this

2022-06-23 08:16 UTC, bentheiii commented on tests/blackbox/image/conftest.py
> +            yield container
retry on the health check instead of sleeping

2022-06-23 08:16 UTC, bentheiii commented on tests/blackbox/image/test_image.py
> +    sleep(5)
don't sleep, retry on the container health

2022-06-23 08:16 UTC, bentheiii commented on tests/blackbox/image/conftest.py
> +def im(docker_client, env_name, env_vars, redis, rabbitmq, blob_storage):
it's called im but it returns a container?

2022-06-23 08:16 UTC, bentheiii commented on tests/unittest/test_blob.py
> +from _pytest.monkeypatch import MonkeyPatch
never import _pytest

2022-06-23 08:16 UTC, bentheiii commented on tests/unittest/test_blob.py
> +                        Mock(wraps=from_connection_string))
```suggestion
                        MagicMock())
```

2022-06-23 08:16 UTC, bentheiii commented on tests/unittest/test_init_messages_processor.py
> +            [redis_hsetnx_mock.assert_called_with(_uid, field, PROFILES[field], redis_mock) for field in PROFILES]
never do this, assert one by one

2022-06-23 08:16 UTC, bentheiii commented on tests/unittest/test_redis.py
> +from _pytest.monkeypatch import MonkeyPatch
_pytest

2022-06-23 08:16 UTC, bentheiii commented on utils/blob.py
> +import asyncio
this entire file should be either deleted or moved into app

2022-06-23 08:16 UTC, bentheiii commented on utils/rabbitmq.py
> +logger = logging.getLogger(('biocatch.' + __name__))
```suggestion
logger = logging.getLogger('biocatch.' + __name__)
```

2022-06-23 08:16 UTC, bentheiii commented on utils/rabbitmq.py
> +import logging
move to app

2022-06-23 08:16 UTC, bentheiii commented on utils/redis.py
> +TIMEOUT = 5000  # ms
better name

2022-06-23 08:16 UTC, bentheiii commented on utils/redis.py
> +import logging
move to app

2022-06-23 08:16 UTC, bentheiii commented on utils/redis.py
> +    await redis.hsetnx(key, field, value)
why?

2022-06-23 08:16 UTC, bentheiii commented on utils/redis.py
> +    return deserialized_profile
do this manually

2022-06-27 07:49 UTC, bentheiii commented on app/initmanager/init_message_consumer.py
> +        await gather(*[aioredis.hset(uid, key, blob_profiles[key]) for key in blob_profiles])
hset can set multiple keys at once

2022-06-27 07:49 UTC, bentheiii commented on app/main.py
> +logger = logging.getLogger('biocatch.' + __name__)
still this

2022-06-27 07:49 UTC, bentheiii commented on app/main.py
> +TIMEOUT = 10000  # ms
better

2022-06-27 07:49 UTC, bentheiii commented on app/main.py
> +import envolved
still this

2022-06-27 07:49 UTC, bentheiii commented on app/main.py
> +        envolved.env_var('redis_port', type=str)
why the line breaks?

2022-06-27 07:49 UTC, bentheiii commented on app/main.py
> +        envolved.env_var('redis_port', type=str)
shouldn't this be an int?

2022-06-27 07:49 UTC, bentheiii commented on app/main.py
> +    return deserialized_profile
why not do hgetall?

2022-06-27 07:49 UTC, bentheiii commented on tests/unittest/test_blob.py
> +from _pytest.monkeypatch import MonkeyPatch
still

2022-06-27 08:19 UTC, AyeletKeren commented on app/main.py
> +        envolved.env_var('redis_port', type=str)
I remember you told me all yellowbox env vars should be string (?..) that's why I used strings

2022-07-17 09:46 UTC, bentheiii commented on app/main.py
> +logger = logging.getLogger('biocatch.ayelet_init_manager')
```suggestion
logger = logging.getLogger('biocatch.' + __name__)
```

2022-07-17 09:46 UTC, bentheiii commented on app/initmanager/init_message_consumer.py
> +                             ds_profiles_pref: str, blob_service_client: BlobServiceClient, redisinst)\
type hint on `redisinst`?

2022-07-17 09:46 UTC, bentheiii commented on app/main.py
> +    redis_port: EnvVar[str] = env_var('redis_port', type=str)
FYI this will work, but there's no reason not to make this an int

2022-07-17 09:46 UTC, bentheiii commented on app/main.py
> +    profiles_decoded = {key.decode(): profiles.get(key) for key in profiles.keys()}
```suggestion
    profiles_decoded = {key.decode(): value for key, value in profiles.items()}
```

2022-07-17 09:46 UTC, bentheiii commented on app/main.py
> +    profiles_decoded = {key.decode(): profiles.get(key) for key in profiles.keys()}
also, these profiles aren't decoded

2022-07-17 09:46 UTC, bentheiii commented on pyproject.toml
>  envolved = "^0.5.0"
envolved isn't dev

2022-07-17 09:46 UTC, bentheiii commented on tests/blackbox/app/test_blackbox.py
> +    response_list = orjson.loads(resp.content.decode())
```suggestion
    response_list = resp.json()
```

2022-07-17 09:46 UTC, bentheiii commented on tests/blackbox/app/test_blackbox.py
> +    assert resp.content == b'"user data missing"'
if it's missing why are you returning OK?
(a general rule of thumb is that each endpoint's OK response should only have one valid schema)

2022-07-19 08:30 UTC, bentheiii commented on app/main.py
> +        return Response(status_code=HTTP_500_INTERNAL_SERVER_ERROR,
you should never return a 500 yourself, 500 is an unhandled exception. in this case a 404 is good

2022-07-19 08:30 UTC, bentheiii commented on app/model.py
> +    data: List[str] = []
why the default?

2022-07-19 09:02 UTC, merged